stages:
  - sync

sync_with_github:
  stage: sync
  before_script:
    - git config --global user.email "amandevani25@gmail.com"
    - git config --global user.name "Aman Devani"
    - git remote -v # Debug: Check existing remotes
  script:
    - git checkout "${CI_COMMIT_REF_NAME}"
    - git pull
    - git remote remove github || true
    - git remote add github "https://oauth2:${GITHUB_TOKEN}@github.com/AmanDevani/${GITHUB_REPO_NAME}.git"
    - git push github "${CI_COMMIT_REF_NAME}"
  only:
    - branches
    - merge_requests
  variables:
    GIT_DEPTH: 0
